### ISSUE TITLE
How to train nmt on GPU

### ISSUE THREAD

**Issue by yzhang123** [lisa-groundhog/GroundHog#46]
Hi, can somebody tell me how to train the nmt on the GPU?
Thanks!

**Comment by nouiz** [comment]
GroundHog isn't maintained anymore. There is another project that replace it. See this warning on github main page of this repo:

WARNING: Groundhog development is over. Please consider using Blocks instead. For an example of machine translation using Blocks please see Blocks-examples repository

Otherwise, see Theano tutorial about GPU: http://deeplearning.net/software/theano/tutorial/using_gpu.html
